# Generated by Django 3.1.6 on 2022-01-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_scraper', '0002_auto_20220119_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(),
        ),
    ]
