# Generated by Django 3.1.6 on 2022-01-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_scraper', '0003_auto_20220119_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.FloatField(),
        ),
    ]
